name: ultical
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.4.0
  math_expressions: ^2.4.0
  http: ^1.0.0
  country_icons: ^2.0.2
  google_fonts: ^5.1.0
  hidden_drawer_menu: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  google_mobile_ads: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ulti_icon.png"
  min_sdk_android: 21 
  cupertino_icons: ^1.0.2

flutter:

  uses-material-design: true

